version: '3.8'

services:
  news-fetcher:
    build: ./news_fetcher
    command: python main.py
    volumes:
      - ./news_fetcher/:/usr/src/news_fetcher/
    env_file:
      - ./.env
    depends_on:
      - db
      - telegram-bot

  telegram-bot:
    build: ./telegram_bot
    command: python bot.py
    volumes:
      - ./telegram_bot/:/usr/src/telegram_bot/
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=telegram_bot
    ports:
      - '5432:5432'

volumes:
  postgres_data: